{
    # All, Layout Modeling, Visual Text Recognition, Joint Text-Layout Reconstruction
    task_name: "Layout Modeling", 

    # Path config
    model_name_or_path: "nielsr/udop-large",  # Path to model weight
    output_dir: "./models",                         # Path to save trained model
    data_dir: "./data",                             # Path to data directory

    # Model config
    max_seq_length: 512,                            
    image_size: 224,
    max_seq_length_decoder: 512,
    model_type: "UdopUnimodel",

    # Task config
    do_train: true,
    do_eval: true,
    do_predict: false,

    # Training config
    num_train_epochs: 10,
    dataloader_num_workers: 4,
    gradient_accumulation_steps: 4,
    per_device_train_batch_size : 1,
    per_device_eval_batch_size : 1,
    overwrite_output_dir: true,
    learning_rate: 5.0e-5,
    warmup_ratio: 0.001,
    weight_decay: 0.001,
    evaluation_strategy: "steps",
    eval_steps: 500,
    logging_steps: 500,
    prediction_loss_only: true,
    label_names: ["labels"],
    save_strategy: "steps",
    save_steps: 2500,
    save_total_limit: 1,
    report_to: 'wandb',

    # tokenize_unit config              # word, token
    unit: "word",

    # learning config
    curriculum: true,                   # true, false
    curri_patience: 10,
    curri_threshold: 0.01,
    curri_start_MR: 0.5,

    # loss config
    loss_fct: "CE",           # CE, MSE, Huber, Custom_huber, GIOU

}